---
- name: install sudo & zsh
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - sudo
      - zsh

- name: add users
  user: name={{ item }} shell='/usr/bin/zsh'
  with_items: "{{ system.users }}"

- name: remove users
  user: name={{ item }} shell='/usr/bin/zsh' state="absent" remove="yes"
  with_items: "{{ system.removed }}"
  when: system.removed is defined

- name: add git user
  user: name=git groups="www-data" append=yes shell="/usr/bin/zsh"

- name: import keys
  action: authorized_key user={{ item }} key="{{ lookup('file', item + '.pub') }}"
  with_items: "{{ system.users }}"
  ignore_errors: yes

- name: add sudoers
  user: name={{ item }} groups='sudo' append=yes
  with_items: "{{ system.sudoers }}"

- name: no password for sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"

- name: import authorized keys for root
  action: authorized_key user=root key="{{ lookup('file', item + '.pub') }}"
  with_items: "{{ system.sudoers }}"

- name: import authorized keys for git
  action: authorized_key user=git key="{{ lookup('file', 'git.pub') }}"
  ignore_errors: yes

- name: zsh for root
  user: name=root shell='/usr/bin/zsh'
